### PR TITLE
Inserting higher quality image

### PR DESCRIPTION
**Pull request by WombleWoo7547**
Changing target to a better target from giphy.

### CODE REVIEW

**Comment by WombleWoo7547** [comment]
@w3cj Just making this appear on your feed
😃 😸 👍 🥇

**Comment by WombleWoo7547** [comment]
@w3cj Just making this appear on your feed
😃 😸 👍 🥇

**Comment by WombleWoo7547** [comment]
@w3cj Just making this appear on your feed
😃 😸 👍 🥇

**Comment by WombleWoo7547** [comment]
@w3cj Just making this appear on your feed
😃 😸 👍 🥇

**Comment by w3cj** [comment]
🌚

**Pull request closed without merging**
